apiVersion: v1
kind: Service
metadata:
  name: {{ include "notifyd.fullname" . }}
  labels:
    {{- include "notifyd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
  nodePort: {{ .Values.service.nodePort }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "notifyd.selectorLabels" . | nindent 4 }}